// Registers brand logos for the app from two folders:
//   apps/mobile/assets/logos/          logos added by hand (these win)
//   apps/mobile/assets/logos-fetched/  logos downloaded by scripts/fetch-logos.mjs
// File names are the merchant key (e.g. swiggy.png, blinkit.png) or bank-<fip id> (e.g. bank-hdfc.png).
// Run after adding or removing logos: npm run logos
import { existsSync, readdirSync, writeFileSync } from 'node:fs';

const assets = new URL('../apps/mobile/assets/', import.meta.url);
const out = new URL('../apps/mobile/src/ui/logos.ts', import.meta.url);
const entries = new Map();
for (const folder of ['logos-fetched', 'logos']) {
  const dir = new URL(`${folder}/`, assets);
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir).filter((x) => /\.(png|jpe?g|webp)$/i.test(x)).sort()) {
    entries.set(f.replace(/\.[^.]+$/, '').toLowerCase(), `../../assets/${folder}/${f}`);
  }
}
const lines = [...entries.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([k, p]) => `  ${JSON.stringify(k)}: require('${p}'),`);
writeFileSync(
  out,
  `// Generated by scripts/gen-logos.mjs — do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

/** Real brand logos keyed by merchant key or \`bank-<fip id>\`. */
export const LOGOS: Record<string, ImageSourcePropType> = {
${lines.join('\n')}
};
`,
);
console.log(`Registered ${entries.size} logo(s).`);
