// Registers every logo in apps/mobile/assets/logos/ for the app.
// File names are the merchant key (e.g. swiggy.png, blinkit.png) or bank-<fip id> (e.g. bank-hdfc.png).
// Run after adding or removing logos: node scripts/gen-logos.mjs
import { readdirSync, writeFileSync } from 'node:fs';

const dir = new URL('../apps/mobile/assets/logos/', import.meta.url);
const out = new URL('../apps/mobile/src/ui/logos.ts', import.meta.url);
const files = readdirSync(dir).filter((f) => /\.(png|jpe?g|webp)$/i.test(f)).sort();
const entries = files.map((f) => `  ${JSON.stringify(f.replace(/\.[^.]+$/, '').toLowerCase())}: require('../../assets/logos/${f}'),`);
writeFileSync(
  out,
  `// Generated by scripts/gen-logos.mjs — do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

/** Real brand logos keyed by merchant key or \`bank-<fip id>\`. */
export const LOGOS: Record<string, ImageSourcePropType> = {
${entries.join('\n')}
};
`,
);
console.log(`Registered ${files.length} logo(s).`);
