// Generated by scripts/gen-logos.mjs — do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

/** Real brand logos keyed by merchant key or `bank-<fip id>`. */
export const LOGOS: Record<string, ImageSourcePropType> = {

};
